# Generated by Django 6.0.3 on 2026-04-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
