# Generated by Django 6.0.3 on 2026-04-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='session_key',
        ),
    ]
